config/routes.rb
Rails.application.routes.draw do

  resources :infos
  root   'sessions#new'
  get    '/',        to: 'static_pages#home'
  get    'home',     to: 'static_pages#home'
  get    '/admin',   to: 'sessions#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :cities
  resources :venues
  resources :events
  resources :bands
  resources :types


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/band.rb
class Band < ApplicationRecord
    has_many :events, dependent: :restrict_with_error
    mount_uploader :imagePath, PictureUploader

#    def description_text
#        Html2Text.convert(description)
#    end



end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all.sort_by(&:name)
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, success: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, success: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
    # Delete image
    if params[:band][:remove_imagePath]
      @band.remove_imagePath!
      @band.save
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, success: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :imagePath, :remove_imagePath, :description, :artistic_director)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_with(model: band, local: true) do |form| %>
  <% if band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :band_name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label 'Image' %><br>
    <% if @band.imagePath? %>
      <%= image_tag(@band.imagePath.url(:standard), alt: 'Image') %>
      <p><%= form.check_box :remove_imagePath, {checked: false}, true, false %>Delete image</p>
    <% else %>
      <%= form.file_field :imagePath, class: "form-control-file" %>
      <small class="form-text text-muted">Recomended size: 600 x 400 pixels.</small>
    <% end %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :band_description, rows: 7, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :artistic_director %>
    <%= form.text_field :artistic_director, id: :band_artistic_director, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success mt-3 mb-3' %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Show', @band, class: 'btn btn-primary' %> |
<%= link_to 'Back', bands_path, class: 'btn btn-primary' %>

app/views/bands/index.html.erb
<% if logged_in? %>

<h1>Bands</h1>

<div class="col-md-10 offset-md-1">
  <div class="table-responsive">
    <table class="table table-hover table-responsive">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Artistic director</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @bands.each do |band| %>
          <tr>
            <td><%= band.name %></td>
            <td><%= sanitize(band.description).truncate(120).html_safe if band.description%></td>
            <td><%= band.artistic_director %></td>
            <td><%= link_to 'Show', band, class: "btn btn-outline-primary btn-sm" %></td>
            <td><%= link_to 'Edit', edit_band_path(band), class: "btn btn-outline-primary btn-sm" %></td>
            <% if band.has_no_restrict_dependent? %>
              <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
            <% else %>
              <td><%= link_to 'Destroy', band, class: "btn btn-outline-danger btn-sm disabled" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>
  <%= link_to 'New Band', new_band_path, class: "btn btn-primary" %>
</div>

<% else %>
  <% controller.redirect_to '/' %>
<% end %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form', band: @band, class: 'btn btn-primary' %>

<%= link_to 'Back', bands_path, class: 'btn btn-primary' %>

app/views/bands/show.html.erb
<% if logged_in? %>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Image:</strong>
</p>
  
<% if @band.imagePath? %>
  <p><%= image_tag(@band.imagePath.url(:standard), alt: 'Image') %></p>
<% else %>
  <p>No image</p>
<% end %>

<p>
  <strong>Description:</strong>
  <%= simple_format(@band.description) %>
</p>

<p>
  <strong>Artistic director:</strong>
  <%= @band.artistic_director %>
</p>

<%= link_to 'Edit', edit_band_path(@band), class: 'btn btn-primary' %> |
<%= link_to 'Back', bands_path, class: 'btn btn-primary' %>

<% else %>
  <% controller.redirect_to '/' %>
<% end %>