config/routes.rb
Rails.application.routes.draw do

  resources :infos
  root   'sessions#new'
  get    '/',        to: 'static_pages#home'
  get    'home',     to: 'static_pages#home'
  get    '/admin',   to: 'sessions#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :cities
  resources :venues
  resources :events
  resources :bands
  resources :types


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/info.rb
class Info < ApplicationRecord
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all.sort_by(&:title)
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, success: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, success: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, success: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:title, :text)
    end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_with(model: info, local: true) do |form| %>
  <% if info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :info_title, class: "form-control"  %>
  </div>

  <div class="field form-group">
    <%= form.label :text %>
    <%= form.text_area :text, id: :info_text, rows: 7, :class => "tinymce" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success mt-3 mb-3" %>
  </div>
<% end %>


<%= tinymce %>

app/views/infos/edit.html.erb
<h1>Editing Info</h1>

<%= render 'form', info: @info %>

<%= link_to 'Show', @info, class: 'btn btn-primary' %> |
<%= link_to 'Back', infos_path, class: 'btn btn-primary' %>

app/views/infos/index.html.erb
<% if logged_in? %>

<h1>Info</h1>

<div class="col-md-8 offset-md-2">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Title</th>
          <th>Text</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @infos.each do |info| %>
          <tr>
            <td><%= info.title %></td>
            <td><%= sanitize(info.text).truncate(60).html_safe %></td>
            <td><%= link_to 'Show', info, class: "btn btn-outline-primary btn-sm" %></td>
            <td><%= link_to 'Edit', edit_info_path(info), class: "btn btn-outline-primary btn-sm" %></td>
            <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>
  <%= link_to 'New Info', new_info_path, class: "btn btn-primary" %>
</div>

<% else %>
  <% controller.redirect_to '/' %>
<% end %>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form', info: @info %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<% if logged_in? %>

<p>
  <strong>Title:</strong>
  <%= @info.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= sanitize @info.text.html_safe if @info.text %>
</p>

<%= link_to 'Edit', edit_info_path(@info), class: 'btn btn-primary' %> |
<%= link_to 'Back', infos_path, class: 'btn btn-primary' %>

<% else %>
  <% controller.redirect_to '/' %>
<% end %>