config/routes.rb
Rails.application.routes.draw do

  resources :infos
  root   'sessions#new'
  get    '/',        to: 'static_pages#home'
  get    'home',     to: 'static_pages#home'
  get    '/admin',   to: 'sessions#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :cities
  resources :venues
  resources :events
  resources :bands
  resources :types


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_accountmenu.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="dropdown float-right account-menu">

            <% if logged_in? %>
                <a class="nav-link dropdown-toggle account-menu" href="" id="navbarDropdownMenuLink" data-toggle="dropdown">
                    Hi, <%= current_user.name %>
                </a>
                <ul class="dropdown-menu" >
                    <li class="dropdown-item"><%= link_to "My Profile", current_user, class: "account-menu-item" %></li>
                    <li class="dropdown-item"><%= link_to "Edit Profile", edit_user_path(current_user), class: "account-menu-item" %></li>
                    <li class="dropdown-divider"></li>
                    <li class="dropdown-item"><%= link_to "Logout", logout_path, method: :delete, class: "account-menu-item" %></li>
                </ul>

            <% else %>
                <ul class="nav-item">
                    <%= link_to "Login", login_path, class: "nav-link" %>
                </ul>        

            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <hr>
  <div  class="text-center">
    <small>
      <%= link_to "Music Festival", home_path, class: "text" %>
      developed by
      <%= link_to "Paulo Belo", "http://github.com/pjbelo", target: :_blank %>
      handcrafted with
      <%= link_to "Ruby on Rails", "http://rubyonrails.org/", target: :_blank %>
       , ©MIT 2018-present
    </small>
  </div>
  <hr>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
    <%= render 'layouts/menu' %>
    <%= render 'layouts/accountmenu' %>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-light bg-light navbar-expand-lg fixed-top">
        <%= link_to home_url, class: "navbar-brand" do %> <strong>Music Fest</strong> <% end %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to "Events", events_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Bands", bands_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Venues", venues_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Cities", cities_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Types", types_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Info", infos_path, class: "nav-link" %>
            </li>
            <% if logged_in? %>
                <li class="nav-item">
                    <%= link_to "Users", users_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= :title.empty? ? "Music Festival" : yield(:title)  %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>" <%= yield(:body_attributes) %> >
    <%= render 'layouts/header' %>
    <div class="container-fluid">

        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>
            <button class="close" data-dismiss="alert">&times;</button>
          </div>
        <% end %>


      <%= yield %>

      <%= render 'layouts/footer' %>

    </div>

    <%= debug(params) if Rails.env.development? %>

  </body>
</html>